---
- name: Download Behat
  command: composer global require behat/behat:\>3.0 creates={{ liara_composer_user_dir }}/vendor/bin/behat

- name: Download Mink
  command: composer global require behat/mink:* creates={{ liara_composer_user_dir }}/vendor/behat/mink/src/Behat/Mink/
- name: Download Mink Drivers
  command: composer global require behat/{{ item }}:* creates={{ liara_composer_user_dir }}/vendor/behat/{{ item }}
  with_items:
    - mink-zombie-driver
    - mink-selenium2-driver
    - mink-goutte-driver

- name: Download PHPSpec
  command: composer global require phpspec/phpspec:* creates={{ liara_composer_user_dir }}/vendor/phpspec